# Generated by Django 5.2.2 on 2025-06-09 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.PositiveIntegerField(help_text='Also equals max number of members')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('invite_token', models.CharField(default='e2fc7125a7e442b8', max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds_hosted', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='funds_joined', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
